#!/bin/sh

. ./test-data

echo "================ PREPARING TEST CARD ================"
$TOOL -a $ADMPIN -u
$TOOL -a $ADMPIN -I $ICCID
$TOOL -a $ADMPIN -J $IMSI
echo "================ TEST CARD PREPARED ================="
echo ""
